### ISSUE TITLE
为什么完成任务之后，积分不会自动增加呢？

### ISSUE THREAD

**Issue by isAlenz** [UxxHans/Rainbow-Cats-Personal-WeChat-MiniProgram#1]
完成任务之后积分不自动增加

**Comment by UxxHans** [comment]
是不是没有修改数据库权限呀

**Comment by isAlenz** [comment]
`{
  "read": true,
  "write": true
}`
是这么写对吧？然后我修改积分的默认值也不会在小程序显示，始终是0

**Comment by AzurOcean** [comment]
我也出现了这样的问题，我看UserList的credit数值是改变了的，但是小程序中显示不出来。不是计算机专业的，求解答。

**Comment by fjqken** [comment]
同样完成任务后没有加积分，已经修改了openid的

**Comment by fjqken** [comment]
去数据库userlist把记录的openid配上就行了

**Comment by xipengpeng** [comment]
各位在添加任务的时候，会有问题，少了一个表

**Comment by UxxHans** [comment]
可能需要数据库的userlist里面加上自己和对象手机的openid 才能成功识别

**Comment by UxxHans** [comment]
新版本已经发出了 里面有如何在数据库了设置openid 希望可以解决这个问题

**Comment by MrVan111** [comment]
openid里面值的添加，直接把从missionlist里的两个id复制粘贴就行了嘛，我复制粘贴完了也没有用……
