### ISSUE TITLE
超过20条任务就显示不出来了，云开发的数据库一次只能获取20条数据，要改用云函数调用数据库才行

### ISSUE THREAD

**Issue by fjqken** [UxxHans/Rainbow-Cats-Personal-WeChat-MiniProgram#10]
![image](https://user-images.githubusercontent.com/31414896/165673469-97507204-3f1b-440f-b935-42c8adfd1edb.png)

**Comment by UxxHans** [comment]
很棒，感谢！

**Comment by h80024** [comment]
我遇见了任务和商城数量显示问题，应该也是云开发一次只能查询20条数据。但是不知道怎么修改，楼主能不能出个详细教程啊！跪求！
