### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by WilmerSit** [UxxHans/Rainbow-Cats-Personal-WeChat-MiniProgram#19]
图片循环播放会增加数据库的读取吗，我好像没怎么打开就超上限500次了

**Comment by WilmerSit** [comment]
![image](https://user-images.githubusercontent.com/30716560/177962299-2199637a-96f8-479e-8858-6c4b6d197210.png)
你好这个问题怎么处理

**Comment by UxxHans** [comment]
不会的 可能数据库传输这块还要优化优化

**Comment by WilmerSit** [comment]
那个逻辑我改好了，对了，这个任务能折叠或展开吗

**Comment by UxxHans** [comment]
还没开发出来 现在所有任务都是全部平铺展示 确实分类折叠会更好

**Comment by UxxHans** [comment]
或者说如果你想折叠展开任务详情 其实可以把那个点进去的详情页和任务页合并

**Comment by UxxHans** [comment]
可以单纯改一下排版的那个文件 看一下开发文档里有没有layout组件可以折叠这样
