### ISSUE TITLE
点商城后报错

### ISSUE THREAD

**Issue by aidandan1314** [UxxHans/Rainbow-Cats-Personal-WeChat-MiniProgram#2]

**Comment by UxxHans** [comment]
报了什么样的错呀
是不是要填一下envId

**Comment by ultraxia** [comment]
![image](https://user-images.githubusercontent.com/25874199/167289899-f4429f52-3947-4050-aabc-af9360e79704.png)
@UxxHans 我这边也是报了错，envID 已经填写了的，请问有什么头绪吗

**Comment by UxxHans** [comment]
新版本和教程已发出 应该能够修复这个问题
