### ISSUE TITLE
怎么给对方增加积分呢？如果是自己操作的话（想修改一下逻辑）

### ISSUE THREAD

**Issue by Emmanuelwh** [UxxHans/Rainbow-Cats-Personal-WeChat-MiniProgram#21]

**Comment by UxxHans** [comment]
修改逻辑的话 可以在cloudfunction里面 或者每页的.js文件里看一看哦 里面有逻辑代码

**Comment by WilmerSit** [comment]
![image](https://user-images.githubusercontent.com/30716560/178959660-1ae507dd-bc17-494a-9d6d-e1121b5a62c4.png)
我是这样改的，就是A给B分任务，A给B积分，能实现，但是不知道这个写法有没有问题
