### ISSUE TITLE
【求助】点击保存任务无响应并报错

### ISSUE THREAD

**Issue by osbornzhou** [UxxHans/Rainbow-Cats-Personal-WeChat-MiniProgram#22]
<img width="678" alt="截屏2022-07-14 20 11 09" src="https://user-images.githubusercontent.com/54236449/178979503-b5e8413e-cf9d-499f-8928-08b1772b4e66.png">
谢谢！

**Comment by osbornzhou** [comment]
添加商城没有任何问题，就是添加任务有报错...

**Comment by osbornzhou** [comment]
<img width="498" alt="截屏2022-07-14 21 40 22" src="https://user-images.githubusercontent.com/54236449/178996022-9d5505b6-259b-4315-a593-7401a5c0c92c.png">
菜单栏从“任务”点到首页的时候会出现另外的报错提醒。。。我大概读了一下，好像是云函数调用失败导致的？那为啥商城的上架是没问题的呀，他不也调用了云函数吗？

**Comment by osbornzhou** [comment]
非常感谢开发者大大！问题解决了，敲的时候少了个i...抱歉浪费您时间啦！orz，（如果方便的话能顺便告知我一下这个是咋发现的吗？

**Comment by UxxHans** [comment]
哈哈不用谢哇 感谢支持 是报错里写“database collection not exist”找到的
