### ISSUE TITLE
【请教】创建任务会出现两条或三条同样的任务

### ISSUE THREAD

**Issue by hhmmmp** [UxxHans/Rainbow-Cats-Personal-WeChat-MiniProgram#23]

**Comment by hhmmmp** [comment]
试了几次，是偶现的~~

**Comment by UxxHans** [comment]
应该是个bug 在添加界面多次点按保存按钮 会触发多次保存 可以通过点了一次按钮变灰来fix

**Comment by SachieWang** [comment]
这种异步的调用感觉还是通过加个toast或者loading来提示，让使用者感知等待比较好，可以同时加上按钮的disable状态

**Comment by cclinpp** [comment]
我是删除完任务之后又会再现出来，每次刷新任务界面上次已经删掉的任务又会再出现，直到删除三次才会没有
