### ISSUE TITLE
卡比进入首页每次都跳不存在的页面

### ISSUE THREAD

**Issue by youaremywind** [UxxHans/Rainbow-Cats-Personal-WeChat-MiniProgram#27]
![IMG_1262](https://user-images.githubusercontent.com/18423358/180218359-a089a291-80e7-42fb-817b-0233684e8ad5.PNG)

**Comment by UxxHans** [comment]
你是不是改了页面的文件名 看样子是因为连接错误而没有找到页面哦 可以在miniprogram/app.json文件里更改页面文件名 这样程序就可以在改文件名或者其他名字之后再次找到页面
