### ISSUE TITLE
你好作者 请问我数据库权限也开了 但是积分不能正常展示

### ISSUE THREAD

**Issue by jl1094000600** [UxxHans/Rainbow-Cats-Personal-WeChat-MiniProgram#28]
按照流程 部署下来 就是积分不能正常展示 只会显示默认值 数据库的积分无法读取

**Comment by UxxHans** [comment]
根据这个错误好像没发定位到问题哦 有没有stacktrace有错误信息可以截图一下 可以检查一下userlist数据库里openid的参数
