### ISSUE TITLE
积分bug

### ISSUE THREAD

**Issue by ccx2205801275** [UxxHans/Rainbow-Cats-Personal-WeChat-MiniProgram#3]
任务完成后积分不会增加，因为MissionList数据库中的start字段不会改变为true(在任务完成时freq字段变为1时)
是否问题没有修复？

**Comment by jw-li** [comment]
> 任务完成后积分不会增加，因为MissionList数据库中的start字段不会改变为true(在任务完成时freq字段变为1时) 是否问题没有修复？

应该是增加积分时openid取错了，修改后正常增加积分。

**Comment by UxxHans** [comment]
是的 应该要修改openid的两个变量

**Comment by UxxHans** [comment]
我觉得可能是因为没有识别到你的openid 因为程序里面有两个地方在app.js和userlist里是要你填上自己的openid
