### ISSUE TITLE
大佬求助，上传的时候显示无依赖文件

### ISSUE THREAD

**Issue by MrVan111** [UxxHans/Rainbow-Cats-Personal-WeChat-MiniProgram#32]
![微信截图_20220803143819](https://user-images.githubusercontent.com/110441699/182541204-eb52b7c9-7744-447d-9a92-6bb04adb4ea0.png)

**Comment by songiro** [comment]
可尝试在`详情 -> 本地设置中关闭上传时过滤无依赖文件`，项目上传后超出大小可删除`miniprogram -> pages 内轮播用到的图片，如HomeCover01.jpg等文件`，同时记得删除对应图片在代码内引用
