### ISSUE TITLE
求助大佬 openid里面值的添加，直接把从missionlist里的两个id复制粘贴就行了嘛

### ISSUE THREAD

**Issue by MrVan111** [UxxHans/Rainbow-Cats-Personal-WeChat-MiniProgram#33]
还是说需要用别的符号隔开，我直接复制了两个发现不可以

**Comment by MrVan111** [comment]
> 还是说需要用别的符号隔开，我直接复制了两个发现不可以
或者说在USERLIST里新建openidA和openidB，积分一直改变不了

**Comment by MrVan111** [comment]
还有就是userlis里的credit一直是0，希望各位大佬帮助，纯小白，不好意思麻烦各位大佬了

**Comment by UxxHans** [comment]
openid 除了userlist里的 其他表格里的全都是自动生成的

**Comment by UxxHans** [comment]
userlist里的openid的值是从missionlist里拷贝过来的

**Comment by liuxing-GitHub-lx** [comment]
人家说的是添加两个记录 然后每个记录保存一个id
