### ISSUE TITLE
【求助】手机端积分无法增长的问题

### ISSUE THREAD

**Issue by stli-prime** [UxxHans/Rainbow-Cats-Personal-WeChat-MiniProgram#35]
### 请问下大佬们体验版任务完成后积分并没有增加怎么解决呢？
不知道下面截图能不能看出问题在哪。之前 4 月份的版本也是遇到这个同样的问题，都是按照教程部署的，翻了翻小红书和以往的 Issues 都没能解决，这次包括修改了```userA userB```之后手机端也无法同步，希望作者大佬空了帮看一下，万分感谢。
![IMG_6928](https://user-images.githubusercontent.com/104419322/182797370-e02562d9-61ba-40cd-8bc8-aeb5f960ecf4.PNG)
![IMG_6929](https://user-images.githubusercontent.com/104419322/182797377-cafc8d0f-a71b-4ea8-b2dc-365277e77e1c.PNG)

**Comment by SachieWang** [comment]
解决了么？
我克隆最新主线代码，正常部署，且使用正常。

建议一下步骤排查
1. 在开发者工具云开发管理面板云函数的日志板块中查看editCredit云函数的调用日志是否都正常。
2. 排查数据库中UserList表中两条记录是否都正确填入openid，并排查miniprogram/app中globalData中的两个openid是否正确填入

**Comment by SachieWang** [comment]
> ### 请问下大佬们体验版任务完成后积分并没有增加怎么解决呢？
> 不知道下面截图能不能看出问题在哪。之前 4 月份的版本也是遇到这个同样的问题，都是按照教程部署的，翻了翻小红书和以往的 Issues 都没能解决，这次包括修改了`userA userB`之后手机端也无法同步，希望作者大佬空了帮看一下，万分感谢。 ![IMG_6928](https://user-images.githubusercontent.com/104419322/182797370-e02562d9-61ba-40cd-8bc8-aeb5f960ecf4.PNG) ![IMG_6929](https://user-images.githubusercontent.com/104419322/182797377-cafc8d0f-a71b-4ea8-b2dc-365277e77e1c.PNG)



> ### 请问下大佬们体验版任务完成后积分并没有增加怎么解决呢？
> 不知道下面截图能不能看出问题在哪。之前 4 月份的版本也是遇到这个同样的问题，都是按照教程部署的，翻了翻小红书和以往的 Issues 都没能解决，这次包括修改了`userA userB`之后手机端也无法同步，希望作者大佬空了帮看一下，万分感谢。 ![IMG_6928](https://user-images.githubusercontent.com/104419322/182797370-e02562d9-61ba-40cd-8bc8-aeb5f960ecf4.PNG) ![IMG_6929](https://user-images.githubusercontent.com/104419322/182797377-cafc8d0f-a71b-4ea8-b2dc-365277e77e1c.PNG)

解决了么？
我克隆最新主线代码，正常部署，且使用正常。

建议一下步骤排查
1. 在开发者工具云开发管理面板云函数的日志板块中查看editCredit云函数的调用日志是否都正常。
2. 排查数据库中UserList表中两条记录是否都正确填入openid，并排查miniprogram/app中globalData中的两个openid是否正确填入

**Comment by SachieWang** [comment]
> ### 请问下大佬们体验版任务完成后积分并没有增加怎么解决呢？
> ......

解决了么？
我克隆最新主线代码，正常部署，且使用正常。

建议一下步骤排查
1. 在开发者工具云开发管理面板云函数的日志板块中查看editCredit云函数的调用日志是否都正常。
2. 排查数据库中UserList表中两条记录是否都正确填入openid，并排查miniprogram/app中globalData中的两个openid是否正确填入

**Comment by youaremywind** [comment]
openid 使用的是本地的文件和你实际的不符合 建议修改后再看

**Comment by stli-prime** [comment]
感谢给位大佬热心解答，感觉确实是上传部署的问题导致文件不同步，重新部署就好了
