### ISSUE TITLE
添加任务或者商品有几率报一定要有积分的错误

### ISSUE THREAD

**Issue by youaremywind** [UxxHans/Rainbow-Cats-Personal-WeChat-MiniProgram#36]
![374711f43941d6eaeee0324688f501d](https://user-images.githubusercontent.com/18423358/182990521-b0e3d707-9bb7-4b61-ba55-b2dc592cd48d.jpg)
这个数值有时候可以正确赋值，有时候不对，会导致有时候选择了积分，缺提示积分不能为0的错误

**Comment by youaremywind** [comment]
![image](https://user-images.githubusercontent.com/18423358/182990958-b8586832-65e1-4169-a650-e38a55a8a8ee.png)

**Comment by SachieWang** [comment]
目测是slider组件的问题(废话😂
感觉只能换用其他组件试试比如iview之类的，还是建议增加提供数字输入的支持，手机上这种拖动组件在大分域小步长的情况下，用户体验不佳

**Comment by youaremywind** [comment]
> 目测是slider组件的问题(废话😂 感觉只能换用其他组件试试比如iview之类的，还是建议增加提供数字输入的支持，手机上这种拖动组件在大分域小步长的情况下，用户体验不佳

是的，我也觉得是你说的这样
