### ISSUE TITLE
保存无响应，点击导航栏报错，大佬求助

### ISSUE THREAD

**Issue by AhriZ08** [UxxHans/Rainbow-Cats-Personal-WeChat-MiniProgram#37]
![image](https://user-images.githubusercontent.com/57840146/182994350-655d3d22-d4df-499c-a52a-91e27ba26d5c.png)
无论是保存还是点击下方导航栏都报这个错误。。。

**Comment by SachieWang** [comment]
云开发环境配置正确么？
云函数都上传部署了么？
可以在云开发管理界面的云函数板块查看下是否有上传的云函数

**Comment by chenmrU** [comment]
我也是这样，云函数已经上传部署

**Comment by AhriZ08** [comment]
![image](https://user-images.githubusercontent.com/57840146/183030222-301d0a60-2b9f-46a3-9830-ea8923ff8636.png)
解决了！直接把app.js中的env填上环境ID即可

**Comment by SachieWang** [comment]
😂属实没想到，你是忘了填这个

**Comment by AhriZ08** [comment]
原来的代码是直接去获取envList.js下的配置字段，但是我的环境下没获取到😂😂，索性就直接替换了
 const normalinfo = require('./envList.js').envList || [] // 读取 envlist 文件
  if (normalinfo.length != 0 && normalinfo[0].envId != null) { // 如果文件中 envlist 存在
    wx.cloud.init({ // 初始化云开发环境
      traceUser: true,
      env: normalinfo[0].envId
    })

**Comment by SachieWang** [comment]
难道开发工具上传小程序端代码传漏了？
