### ISSUE TITLE
小程序积分bug

### ISSUE THREAD

**Issue by AzurOcean** [UxxHans/Rainbow-Cats-Personal-WeChat-MiniProgram#4]
您好！非常感谢您的小程序代码。
但是我在使用时发现云端Userid中credit数值已经改变，但是小程序中数值未变（均为0）。
请问如何解决？

**Comment by lmh-leo** [comment]
但是在开发时云端数值是同步了的，手机上不行。

**Comment by lmh-leo** [comment]
在开发界面设置-项目设置-调试基础库改为2.23.4之后就好了

> 您好！非常感谢您的小程序代码。 但是我在使用时发现云端Userid中credit数值已经改变，但是小程序中数值未变（均为0）。 请问如何解决？

**Comment by UxxHans** [comment]
新版已发出 修复了之前的一些bug 新版使用了云函数 应该可以解决这个问题 欢迎尝试
