### ISSUE TITLE
建议优化一下项目文件

### ISSUE THREAD

**Issue by schizobulia** [UxxHans/Rainbow-Cats-Personal-WeChat-MiniProgram#40]
最近在开发一个小程序静态扫描器，然后有一些小建议😊

- images/Item.gif 文件大于200k
- miniprogram_npm/weui-miniprogram/badge/badge.wxss 文件为空
- miniprogram_npm/weui-miniprogram/slideview/slideview.wxss 文件为空
- pages/Market/Images/MarketCover.jpg 文件可能没有被使用

[检查器](https://www.npmjs.com/package/weapp_fc)

**Comment by UxxHans** [comment]
感谢建议! 最近工作很忙 有时间的话可以帮我清理补充一下 成为contributor 谢谢!
