### ISSUE TITLE
萌新求助，代码包过大上传不了，自己又不敢乱改

### ISSUE THREAD

**Issue by Ggangster888888** [UxxHans/Rainbow-Cats-Personal-WeChat-MiniProgram#42]

**Comment by SachieWang** [comment]
最简单有wps就够了，wps有压缩图片功能，你把miniprogram/ 下所有的images里面的png、jpg都压缩一下大小就可以了。

**Comment by lightislost** [comment]
把miniprogram/images/下面的两个gif图上传到云开发的存储里，然后搜索代码中  Item.git和Mission.gif  的位置，把他们替换成 存储的gif地址，再把那两个gif删掉就可以了
