### ISSUE TITLE
积分无法获得

### ISSUE THREAD

**Issue by Tangerinrs** [UxxHans/Rainbow-Cats-Personal-WeChat-MiniProgram#43]
想问一下大佬 其他一切正常 但是积分无法正常获取
_openid字段是两个变量逗号分开还是userlist在创建一条默认记录
所以想请教一下两个openid是分开写还是需要写在一起
<img width="707" alt="image" src="https://user-images.githubusercontent.com/74159972/183534389-a93c6c7d-8c89-4b93-8bbe-0ddf2d06b2c5.png">

**Comment by SachieWang** [comment]
你的openid就这么贴出来了？

分开写，写在userlist不同的记录里
你积分获取不正常，我看可能是你openid最后多了一个引号引起的

**Comment by Tangerinrs** [comment]
好的 已经解决了 谢谢您
