### ISSUE TITLE
【待优化】需要增加个用户绑定逻辑

### ISSUE THREAD

**Issue by JonSnow6** [UxxHans/Rainbow-Cats-Personal-WeChat-MiniProgram#44]
需要开发者自己去复制opendi 这个限制了 使用范围啊，应该增加个用户绑定逻辑，可以分享给对应的朋友，朋友点击后拿到openid再绑定，如果再深入的话 可以做的像共享记账本一样 可以修改共享者；

**Comment by UxxHans** [comment]
是啊 这个我也想过 但是没啥时间做

**Comment by git1126** [comment]
如何才能联系到作者,请教一下,其他功能,想实现一下其他功能
