### ISSUE TITLE
【求助】添加任务和添加商品的保存均出现问题

### ISSUE THREAD

**Issue by CHXILINENG** [UxxHans/Rainbow-Cats-Personal-WeChat-MiniProgram#45]
在添加新任务和新商品的时候会遇到[保存]按钮点击了但是没有反应的情况，重置可以点击
![问题1](https://user-images.githubusercontent.com/101179933/184332640-9e908f56-c8df-4b16-81ab-cef97b06d422.png)
![问题2](https://user-images.githubusercontent.com/101179933/184332653-2fd5e146-02fb-4486-9bbc-5510b2ee608a.png)
![问题3](https://user-images.githubusercontent.com/101179933/184332657-516ed0f5-5bc9-4f7d-bdc4-f27778bf830b.png)

**Comment by liuyongjie2001** [comment]
没解决了吗？

**Comment by liuyongjie2001** [comment]
你解决了吗？

**Comment by yyyyagagggas** [comment]
我也是这个问题，有没有大佬教一下

**Comment by liuyongjie2001** [comment]
这是目录选错了，重新选择主目录
