### ISSUE TITLE
发布任务让对方完成然后自己监督给对方加分

### ISSUE THREAD

**Issue by faker-netizen** [UxxHans/Rainbow-Cats-Personal-WeChat-MiniProgram#46]
原来是A发布A自己完成B监督，成功给A自己加分
能不能也有一个A发布任务让B完成，成功给B加分呢~
求求了~

**Comment by ZFYy1x** [comment]
原来是这样啊，怪不得我说积分怎么自己发任务自己涨

**Comment by lightislost** [comment]
https://gitee.com/lightislost/couple-daily-task-applet

**Comment by zhufacai** [comment]
对的这样才更有趣一点

**Comment by UxxHans** [comment]
感谢支持 有机会我会优化的
