### ISSUE TITLE
求助求助

### ISSUE THREAD

**Issue by guo131528** [UxxHans/Rainbow-Cats-Personal-WeChat-MiniProgram#49]
![Screenshot_20220820_174153_com tencent mm](https://user-images.githubusercontent.com/111405792/185739612-8253740f-7bf4-4628-987f-21d7db6a3bb1.jpg)
![Uploading Screenshot_20220820_174143_com.tencent.mm.jpg…]()
为什么我的没有确定按钮呢

**Comment by UxxHans** [comment]
在任务列表 左滑任务
