### ISSUE TITLE
你好~我遇到商城的一些问题

### ISSUE THREAD

**Issue by ph1xxx** [UxxHans/Rainbow-Cats-Personal-WeChat-MiniProgram#5]
商城购买商品时出错，A买B设置的商品时扣除了B的积分？其他功能均没有问题，想请教下怎么解决？

**Comment by XH1025** [comment]
我出现的是A做B给的任务，积分到B那里去了，中途改了个数据库id然后也出现楼上的问题，但是任务就好了，还请大佬出现解决

**Comment by Soda00** [comment]
// Add Credit
        db.collection(getApp().globalData.collectionUserList).where({
          _openid: openid

这个部分改一下就行了

**Comment by fjqken** [comment]
> ```
>     // Add Credit
>     db.collection(getApp().globalData.collectionUserList).where({
>       _openid: openid
> ```
> 
> 这个部分改一下就行了

这个改了没用啊

**Comment by UxxHans** [comment]
新版已发布 修复了bug增强了功能和视觉 欢迎尝试
