### ISSUE TITLE
如何才能联系到作者,想请教下作者

### ISSUE THREAD

**Issue by git1126** [UxxHans/Rainbow-Cats-Personal-WeChat-MiniProgram#55]
想请教下作者,我想在作者的基础上在加一些新功能模块,我的qq1126440096,还请作者加我下

**Comment by UxxHans** [comment]
我不用qq要不加我微信吧 Zzzhans

**Comment by UxxHans** [comment]
> 想请教下作者,我想在作者的基础上在加一些新功能模块,我的qq1126440096,还请作者加我下

好呀 多加点功能肯定很有趣
