### ISSUE TITLE
改成网页端使得不用云收费，学生全程免费

### ISSUE THREAD

**Issue by Yanyutin753** [UxxHans/Rainbow-Cats-Personal-WeChat-MiniProgram#68]
云开发涨价太贵了，自己写了一个网页端的，部署地址：https://github.com/Yanyutin753/shop-task-forlovers
全程免费，就只用出个域名钱，阿里云还可以定制域名，才几块钱 
给我点星星吧！

**Comment by UxxHans** [comment]
这个不错 我喜欢 谢谢credit

**Comment by Yanyutin753** [comment]
🥳🥳🥳

**Comment by Yanyutin753** [comment]
谢谢作者给的灵感，开始都是用的作者大大的小程序，后面云开发涨价了🥹🥹🥹
