### ISSUE TITLE
云端依赖

### ISSUE THREAD

**Issue by zzyy6666** [UxxHans/Rainbow-Cats-Personal-WeChat-MiniProgram#8]
右键点击 cloudfunctions/getOpenId 文件夹，选择云函数云端安装依赖上传，这一步是怎么操作的，求解

**Comment by clyzhzh** [comment]
我是在cloudfunctions文件夹右键选择环境：link，然后再 cloudfunctions/getOpenId 文件夹选择云函数云端安装依赖上传，你可以试试
