### ISSUE TITLE
完成任务后的积分增加逻辑

### ISSUE THREAD

**Issue by tianzhenqing** [UxxHans/Rainbow-Cats-Personal-WeChat-MiniProgram#9]
deeOpenId发布的任务.
kirbyOpenId点击完成任务后，积分加到了deeOpenId上。是逻辑就是这样的吗？

**Comment by sht-0828** [comment]
同问

**Comment by ahahou3** [comment]
不是哦，看一眼pull request就知道怎么改了

**Comment by UxxHans** [comment]
打个比方:
女朋友发布任务->女朋友来做任务->做完后由你来确认完成->女朋友收到积分

你发布商品(洗碗券)->女朋友使用积分购买->商品进入到女朋友的库存->女朋友拿着洗碗券叫你洗碗->你洗碗->女朋友将物品(洗碗券)标记为已使用(不可逆)

这样做的原因是 不想给任何一方能自说自话 增加自己或者对方积分的能力
